# Generated by Django 3.0.8 on 2020-07-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formcms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
